version: '3.8'
services:
  redis:
    image: redis:5
    container_name: caching-redis
    hostname: caching-redis
    restart: always
    networks:
      - caching-demo
  api:
    build:
      context: .
    env_file:
      - .env
    image: caching-api
    container_name: caching-api
    ports:
    - 5000:5000
    volumes:
    - ./public:/public
    restart: always
    depends_on:
      - redis
    networks:
      - caching-demo
networks:
  caching-demo:
    driver: bridge

